# Generated by Django 3.0.7 on 2020-06-07 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awwardsapp', '0003_auto_20200607_1348'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='location',
            field=models.CharField(default='World', max_length=20, unique=True),
        ),
    ]
