# Generated by Django 2.1.5 on 2020-06-09 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awwardsapp', '0009_auto_20200609_1433'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
